"""Add audio_file_path to Question

Revision ID: b4d4b6f10333
Revises: 15f498739d58
Create Date: 2024-09-03 18:04:51.502598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d4b6f10333'
down_revision = '15f498739d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('audio_file_path')

    # ### end Alembic commands ###
